-- 0006_permits.sql — permit-to-work with hazard assessment and structured controls.

create table public.permits (
  id uuid primary key default gen_random_uuid(),
  permit_number text not null unique,
  depot_id uuid not null references public.depots(id) on delete cascade,
  permit_type text,
  job_title text not null,
  job_description text,
  tasks jsonb not null default '[]',
  location text,
  start_datetime timestamptz,
  end_datetime timestamptz,
  hazard_assessment jsonb not null default '[]',
  additional_controls text,
  ppe jsonb not null default '[]',
  isolation_loto text,
  gas_tests jsonb not null default '{"readings":[],"test_equipment":"","calibrated":false}',
  confined_space jsonb not null default '{"is_confined_space":false,"entry_permit":false,"gas_monitor":false,"rescue_plan":false}',
  work_at_height jsonb not null default '{"is_work_at_height":false,"harness":false,"anchored_100pct":false,"guardrails":false,"scaff_tag":""}',
  electrical_isolation jsonb not null default '{"isolation_required":false,"lockout_tags":0,"permits_issued":false}',
  excavation jsonb not null default '{"is_excavation":false,"depth_meters":0,"shoring":false,"buried_services":false,"utility_clearance":false}',
  certificates jsonb not null default '[]',
  attachment_paths text[] not null default '{}',
  signature_applicant text,
  signature_approving text,
  status public.permit_status not null default 'DRAFT',
  rejection_reason text,
  approved_at timestamptz,
  approved_by uuid references public.profiles(id) on delete set null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);